groups:
  default:
    default: true
    permissions:
    - ee.lutsu.alpha.mc.mytown.commands.*
    - mbr.*
    - modifyworld.*
    - -mytown.adm.bypass.teleportwait
    - –mytown.adm.cmd.tp
    - mytown.resident.blocksmulti.4
    - mytown.adm.cmd.*
    - mytown.chat.*
    - mytown.ecmd.*
    - mytown.cmd(|.*)
    - mytown.*
    - mytown.adm.*
    - permissions.*
    - essentials.*
    prefix: '[Citizen] '
  Master:
    inheritance:
    - default
    prefix: '[Master] '
  Admin:
    inheritance:
    - default
    permissions:
    - mytown.adm.bypass.teleportwait
    - '*'
    prefix: '[Lord] '
users:
  BadMonkeyMC:
    group:
    - Admin
  samb123:
    group:
    - Master
  TwistedRapier:
    group:
    - Master